name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake valgrind lcov
    - name: Build
      run: make
    - name: Run Unit Tests
      run: make test || ./tests/test_suite
    - name: Debug Directory Content
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in ./test:"
        ls -la ./test
        echo "Files in ./src:"
        ls -la ./src
    - name: Verify Coverage Files
      run: |
        echo "Checking for .gcda files:"
        find . -name "*.gcda" || echo "No .gcda files found!"
    - name: Run test
      run: make run_test
    - name: Generate Coverage Report
      run: lcov --capture --directory test --output-file coverage.info

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: coverage.info
        token: ${{ secrets.CODECOV_TOKEN }}
    # - name: norm
    #   run: make norm
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
