name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake valgrind
    - name: Build
      run: make
    - name: Run Unit Tests
      run: make test || ./tests/test_suite
    # - name: norm
    #   run: make norm
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
